### PR TITLE
AN-118 Material UI cats

### PR DESCRIPTION
**Pull request by ApplebaumIan**
This is where we left off in class as an example. 
- Cats update when you click the meow button
- The Meow button and Search button are Material UI Components
- Search Button switches main app component to `<Search />`

Other stuff:
- Dockerfile builds a production ready container of the React App

### CODE REVIEW

**Comment by ApplebaumIan** [comment]
Notice GitHub is suggesting to automate the Docker build!
Screen Shot 2022-04-07 at 3 33 02 PM

**Comment by fayloads** [comment]
Do we have a limit on the automated docker builds?

**Comment by ApplebaumIan** [comment]
@avariantphi As an Open Source student project I don't think so

**Comment by ApplebaumIan** [comment]
Also we can use Electric Bluefish Productions' Docker Hub Account.

**Pull request merged**
